# Generated by Django 4.2.6 on 2023-10-13 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trends', '0002_alter_trend_seach_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trend',
            name='seach_period',
            field=models.DurationField(),
        ),
    ]
